# Generated by Django 3.2.15 on 2023-01-29 07:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(db_index=True, max_length=100)),
                ('city', models.CharField(db_index=True, max_length=20)),
                ('purpose', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'pet owner',
                'verbose_name_plural': 'pet owners',
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(db_index=True, max_length=100)),
                ('manager', models.CharField(max_length=100)),
                ('city', models.CharField(db_index=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'shelter',
                'verbose_name_plural': 'shelters',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='PetInShelter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('breed', models.CharField(db_index=True, max_length=100)),
                ('nickname', models.CharField(db_index=True, max_length=100)),
                ('sex', models.CharField(max_length=1)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('shelter_field', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.PROTECT, to='mainapp.shelter')),
            ],
            options={
                'verbose_name': 'pet',
                'verbose_name_plural': 'pets in shelters',
                'ordering': ['breed'],
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('breed', models.CharField(db_index=True, max_length=100)),
                ('nickname', models.CharField(db_index=True, max_length=100)),
                ('age', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('sex', models.CharField(max_length=1)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('owner_field', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.PROTECT, to='mainapp.owner')),
            ],
            options={
                'verbose_name': 'pet',
                'verbose_name_plural': 'pets',
                'ordering': ['breed'],
            },
        ),
    ]
