# Generated by Django 3.2.15 on 2022-11-25 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='my_pet',
        ),
    ]
