# Generated by Django 3.2.15 on 2022-12-09 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_remove_owner_my_pet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='owner',
            options={'ordering': ['first_name'], 'verbose_name': 'pet owner', 'verbose_name_plural': 'pet owners'},
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='full_name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='owner',
            name='last_name',
            field=models.CharField(db_index=True, default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='owner',
            name='city',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pet',
            name='nickname',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
