# Generated by Django 3.2.15 on 2022-12-09 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20221209_2245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='owner',
            options={'ordering': ['first_name', 'last_name'], 'verbose_name': 'pet owner', 'verbose_name_plural': 'pet owners'},
        ),
    ]
