# Generated by Django 3.2.15 on 2022-12-10 11:59

from django.db import migrations, models
import django.db.models.deletion
import mainapp.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_owner_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetShelter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100)),
                ('manager', models.CharField(max_length=100)),
                ('city', models.CharField(db_index=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'pet shelter',
                'verbose_name_plural': 'pet shelters',
                'ordering': ['title'],
            },
            bases=(models.Model, mainapp.mixins.SoftDateTimeMixin),
        ),
        migrations.RemoveField(
            model_name='owner',
            name='create_at',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='create_at',
        ),
        migrations.CreateModel(
            name='PetInShelter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.CharField(db_index=True, max_length=100)),
                ('nickname', models.CharField(db_index=True, max_length=100)),
                ('sex', models.CharField(max_length=1)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('shelter', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.PROTECT, to='mainapp.petshelter')),
            ],
            options={
                'verbose_name': 'pet',
                'verbose_name_plural': 'pets',
                'ordering': ['breed'],
            },
            bases=(models.Model, mainapp.mixins.SoftDateTimeMixin),
        ),
    ]
