# Generated by Django 3.2.15 on 2022-12-11 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20221210_1459'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PetShelter',
            new_name='Shelter',
        ),
        migrations.AlterModelOptions(
            name='shelter',
            options={'ordering': ['title'], 'verbose_name': 'shelter', 'verbose_name_plural': 'shelters'},
        ),
    ]
