# Generated by Django 3.2.15 on 2022-12-11 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20221211_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelter',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
